ci/environment-py3.7.yml
ci/environment-py3.8.yml
climate_index_collection/data_loading.py
tests/test_data_loading.py

Add data loading functions

---

tests/test_SAM.py

set up test_SAM.py to test SAM index

---

climate_index_collection/indices.py
climate_index_collection/reductions.py
tests/test_reductions.py

Abstract away reductions

---

tests/test_indices.py

Make sure we test for name

---

.gitignore
ci/environment-py3.7.yml
ci/environment-py3.8.yml
climate_index_collection/__main__.py
climate_index_collection/cli.py
environment.yml
setup.cfg
tests/test_cli.py

This adds a basic and not yet functional command line interface (CLI) to the package.
Addresses #21

Add command line interface

---

climate_index_collection/cli.py
climate_index_collection/indices.py
tests/test_cli.py
tests/test_indices.py

Add end-to-end workflow

---

climate_index_collection/output.py

Fix docstrings

---

climate_index_collection/indices.py

Update documentation of index calculations

---

README.md

Remove badges we won't use in the near future.

Remove unnecessary badges

---

data/test_data/extract_test_data.sh

Remove TEMP attribute and only keep SALT, plus modify shell script accordingly

Modify SSS test data for CESM

---

climate_index_collection/indices.py

Currently the area-averaging is still included implicitly inside the index function. Will be modified later (see #58).

Simplify ENSO3.4 index

---

tests/test_indices.py

closes issue #59 
testing of ENSO 3.4 having zero mean

refactored enso34 testing - zero mean (#59)

---

climate_index_collection/data_loading.py
climate_index_collection/timestamp_handling.py
pyproject.toml
tests/test_data_loading.py
tests/test_timestamp_handling.py

Closes #73 
Not remotely ready. Nonstandard Calendars really make stuff difficult....

Fix timestamp issues (mid month labelling and wrong year labelling in CESM)

---

climate_index_collection/indices.py
tests/test_indices.py

Add index definition and tests.
Note: This index only works correctly as soon as #73 is solved. Then closes #63.

Add nao index pc based

---

climate_index_collection/reductions.py

removed the unused and not tested monthly weighted functions 
See #66

removed the unused and not tested monthly weighted functions

---

climate_index_collection/data_loading.py
tests/test_data_loading.py

Mask missing data

---

climate_index_collection/indices.py

Disable Principal-Component Indices

---

climate_index_collection/indices.py

Fix PC-based SAM and NAO indices to be able to handle full data

---

data/test_data/extract_test_data.sh

Modify indexing in script to extract test data to start from step ZERO. Closes #108

Fix test data

---

climate_index_collection/indices.py
tests/test_indices.py

Add further indices: Sahel Precipitation and Pacific Decadal Oscillation

---

climate_index_collection/indices.py
tests/test_indices.py

- ENSO indices for Nino1+2, Nino3 and Nino4 regions (Closes #112)

Add further indices

---

.pre-commit-config.yaml

See https://github.com/PyCQA/flake8/issues/1737

Update flake8 repo URL

---

README.md

@MarcoLandtHayen Please have a look and adapt if necessary.

Draft quickstarts
